language: node_js
node_js:
  - "4"
# travis encrypt [subdomain]:[api token]@[room id]
# notifications:
#   email: false
#   campfire:
#     rooms:
#       secure: xyz
#     on_failure: always
#     on_success: always
